  [[main]]
  name = "INÍCIO"
  identifier = "home"
  weight = 100
  url = "/inicio/"

  [[main]]
  name = "PROJETOS"
  weight = 300
  identifier = "projetos"
  url = "/projetos/"

  [[main]]
  name = "DOCÊNCIA"
  weight = 400
  identifier = "docencia"
  url = "/docencia/"

  [[main]]
  name = "PUBLICAÇÕES"
  weight = 510
  identifier = "publicacoes"
  url = "/publicacoes/"

  [[main]]
  name = "TESES"
  weight = 520
  identifier = "teses"
  url = "/teses/"

  [[main]]
  name = "CONTATO"
  weight = 600
  identifier = "contato"
  url = "/contato/"

  [[footer]]
  name = "Adaptado de anatole"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"